project_id = "kpvziakutvzsmrnsvevi"

[functions.initiate-payment]
verify_jwt = true

[functions.generate-receipt]
verify_jwt = true

[functions.check-payment-reminders]
verify_jwt = false

[functions.bedroom-designer]
verify_jwt = true

[functions.generate-monthly-rent-invoices]
verify_jwt = false
